import type { Metadata } from "next";
import { KoHo, Poppins } from 'next/font/google';
import "./globals.css";

const koho = KoHo({
  subsets: ['latin'],
  variable: '--font-koho',
  display: 'swap',
  weight: ["200", "300", "400", "500", "600", "700"],
});
const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${koho.variable} ${poppins.variable} antialiased`}>
      <body className="font-koho">
        {children}
      </body>
    </html>
  );
}
